# from tensorflow 2.0.0 gpu py3 jupyter
FROM 88178d65d12c

RUN pip install --upgrade \
    pip \
    setuptools

RUN pip3 install jupyterlab==1.1.4 \
                 pandas==0.25.1 \
                 numpy==1.17.2 \
                 scikit-learn==0.21.1 \
                 tqdm==4.36.1 \
                 matplotlib==3.1.1 \
                 seaborn==0.9.0 \
                 scipy==1.3.1
